### PR TITLE
Action to label PRs with merge conflicts

### PR DESCRIPTION
**Pull request by martinlyra**
Basically what the title says

Cargo-culted from a SS13 codebase.

### CODE REVIEW

**Comment by martinlyra** [comment]
The comment has been removed. Took longer because I got no more feedback regarding this. But that should be fixed now.

**Comment by wixoaGit** [comment]
Do I need to make a "Merge Conflict" label for this to work?

**Comment by martinlyra** [comment]
I don't know. But for a good measure and to be on the safe side, do it.

**Comment by ZeWaka** [comment]
> Do I need to make a "Merge Conflict" label for this to work?

Yes.

**Comment by ZeWaka** [comment]
I'd recommend using my fork, since it's faster (pulls image from dockerhub) and also allows for customizable retries, which is very useful when github is being shit.
ex.
```yml
      - uses: zewaka/auto-label-merge-conflicts@master
        with:
          CONFLICT_LABEL_NAME: "merge conflict"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAX_RETRIES: 12
          WAIT_MS: 8008
```

**Comment by martinlyra** [comment]
Fork has been changed from `eps1lon`'s fork to Zewaka's as recommended.

**Review by wixoaGit — APPROVED** [review]

**Comment by wixoaGit** [comment]
I'm reverting this because it's both causing issues with CI & we don't have much of a use for it at this moment.

**Pull request merged**
