### PR TITLE
Removes every `HasFlag()`

### PR DESCRIPTION
**Pull request by ike709**
Correct me if I'm wrong, but `HasFlag()` uses boxing, which is slow.

### CODE REVIEW

**Comment by wixoaGit** [comment]
Do any of these usages of `HasFlag` run often enough for it to be a performance concern?

**Comment by ike709** [comment]
I haven't checked, but is there any actual reason *not* to just change it?

**Comment by ZeWaka** [comment]
Do you know that it boxes or are you just guessing? That's how the PR reads to me.

**Comment by ike709** [comment]
@ZeWaka https://medium.com/@arphox/the-boxing-overhead-of-the-enum-hasflag-method-c62a0841c25a

**Comment by ike709** [comment]
https://stackoverflow.com/questions/7368652/what-is-it-that-makes-enum-hasflag-so-slow

**Review by wixoaGit — APPROVED** [review]

**Pull request merged**
