### PR TITLE
Implement spawn, goto, and label simplifiers

### PR DESCRIPTION
**Pull request by ike709**
Dipping my toes into DMASTSimplifier.

### CODE REVIEW

**Review by wixoaGit — CHANGES_REQUESTED** [review]
The line `statementSpawn.Body.Visit(this)` should be added

**Comment by wixoaGit** [comment]
It won't go through the spawn's body and visit its statements without it

**Comment by ike709** [comment]
Interesting. Anything else need changing?

**Comment by wixoaGit** [comment]
Nope, should be good

**Review by wixoaGit — APPROVED** [review]

**Pull request merged**
