### PR TITLE
Adds a GitHub Action for CI

### PR DESCRIPTION
**Pull request by ike709**
You'll have to create the actual GitHub Action yourself, but here's a yaml file with everything for some basic CI.

### CODE REVIEW

**Comment by ike709** [comment]
Hold on I PRed the wrong branch.

**Comment by wixoaGit** [comment]
So this should detect when there are errors in DMCompiler or TestGame? What changes to the compiler would need to be made for it to detect compile errors in TestGame?

**Comment by ike709** [comment]
This will detect regular unhandled C# exceptions or an exit code of 1. You should set it to exit with 1 whenever there are compile errors. See https://stackoverflow.com/questions/155610/how-do-i-specify-the-exit-code-of-a-console-application-in-net

**Comment by ike709** [comment]
Here is a test commit I made with a missing `"`: https://github.com/ike709/OpenDream/pull/2/commits/6c585975f7f7d1c115cfea4d44c76f2fc5707085

**Comment by ike709** [comment]
Note that rather than merging this PR, you need to click the repo's Actions tab and create the yaml file yourself (just copypaste mine).

**Comment by ike709** [comment]
Also this makes sure all 3 projects will can be compiled by dotnet.

**Comment by ike709** [comment]
Looks fine. If you want to test it open a PR that intentionally breaks the DM code's ability to compile.

**Pull request closed without merging**
